---
title: "Middlebury placement assessment"
author: "Joseph V. Casillas"
date: today
execute: 
  warning: false
  message: false
  echo: false
---

```{r}
#| label: setup
source(here::here("scripts", "01_helpers.R"))
source(here("scripts", "99_small_data.R"))
```

Links to scripts: 

```{r}
#| label: toc
#| results: 'asis'

dir_ls(here("scripts"), regexp = ".html") |> 
  as_tibble() |> 
  mutate(
    value = str_remove(value, pattern = here("")), 
    topic = str_remove(value, pattern = "scripts/"), 
    topic = str_remove(topic, pattern = "(\\d+)_"), 
    topic = str_remove(topic, pattern = ".html"), 
    topic = str_replace_all(topic, "_", " "), 
    topic = str_to_sentence(topic), 
    link = glue("- [{topic}]({value})")
  ) |> 
  pull(link)
```


Current status: 


```{r}
#| label: tbl-status

n_s |> 
  select(year, everything()) |> 
  knitr::kable()
```

Current predictions: 

```{r}
#| label: tbl-preds
#| results: 'asis'

temp <- readRDS(here("data", "tidy", "preds_2024.rds")) |> 
  select(id, level_1, level_1.5, level_2, level_3, level_4, master) |> 
  pivot_longer(cols = -id, names_to = "level", values_to = "vals") |> 
  mutate(
    level = str_replace(level, "_", " "), 
    level = str_to_sentence(level)
    ) |> 
  pivot_wider(names_from = "level", values_from = "vals") |> 
  as.data.frame()
 
ztable(temp, size = 5) |> 
  makeHeatmap(palette = "Blues", margin = 1)

```

